services:
  postgres:
    image: postgres:16
    container_name: serene_postgres
    restart: always
    environment:
      POSTGRES_USER: dockerlocal
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: serene
    ports:
      - "5431:5432"
    volumes:
      - serene_data:/var/lib/postgresql/data
    networks:
      - serene_net

volumes:
  serene_data:

networks:
  serene_net:
    driver: bridge
